[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "light-pattern-designer"
version = "1.0.0"
description = "Light Pattern Designer GUI Application"
requires-python = ">=3.10"
dependencies = [
    "flet>=0.28.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]